# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-19 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('db_id', models.IntegerField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DBTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('r_name', models.CharField(max_length=20)),
                ('db_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TDataApp.Database')),
            ],
        ),
        migrations.CreateModel(
            name='DBTAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.IntegerField()),
                ('a_name', models.CharField(max_length=20)),
                ('a_type', models.CharField(max_length=20)),
                ('is_temp', models.BooleanField()),
                ('db_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TDataApp.Database')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TDataApp.DBTables')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dbtattribute',
            unique_together=set([('db_id', 'r_id', 'a_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='dbtables',
            unique_together=set([('db_id', 'r_id')]),
        ),
    ]
