# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-20 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TDataApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('dt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_name', models.CharField(max_length=20)),
            ],
        ),
    ]
