# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-21 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TDataApp', '0002_datatypes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dbtables',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='dbtattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dbtattribute',
            name='db_id',
        ),
    ]
